# Generated by Django 5.0.1 on 2024-03-30 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('colorCode', models.CharField(max_length=100, null=True, verbose_name='کد رنگ')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='عنوان در Url')),
                ('isActive', models.BooleanField(verbose_name='فعال/غیر فعال')),
                ('isDelete', models.BooleanField(verbose_name='حذف شود/حذف نشود')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ ها',
            },
        ),
        migrations.CreateModel(
            name='SizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='عنوان در Url')),
                ('isActive', models.BooleanField(verbose_name='فعال/غیر فعال')),
                ('isDelete', models.BooleanField(verbose_name='حذف شود/حذف نشود')),
            ],
            options={
                'verbose_name': 'سایز',
                'verbose_name_plural': 'سایز ها',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('image', models.ImageField(null=True, upload_to='images/category/', verbose_name='عکس')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='عنوان در Url')),
                ('isActive', models.BooleanField(verbose_name='فعال/غیر فعال')),
                ('isDelete', models.BooleanField(verbose_name='حذف شود/حذف نشود')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productsModule.categorymodel', verbose_name='دسته بندی اصلی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('discount', models.IntegerField(null=True, verbose_name='درصد تخفیف')),
                ('count', models.IntegerField(verbose_name='تعداد در انبار')),
                ('brand', models.CharField(max_length=100, null=True, verbose_name='برند')),
                ('country', models.CharField(max_length=200, null=True, verbose_name='کشور')),
                ('seller', models.CharField(max_length=200, null=True, verbose_name='فروشنده')),
                ('shortDes', models.TextField(null=True, verbose_name='توضیحات کوتاه')),
                ('sell_count', models.IntegerField(default=0, verbose_name='مقدار فروش')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='عنوان در Url')),
                ('isActive', models.BooleanField(verbose_name='فعال/غیر فعال')),
                ('isDelete', models.BooleanField(verbose_name='حذف شود/حذف نشود')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsModule.categorymodel', verbose_name='دسته بندی')),
                ('color', models.ManyToManyField(blank=True, to='productsModule.colormodel', verbose_name='رنگ ها')),
                ('size', models.ManyToManyField(blank=True, to='productsModule.sizemodel', verbose_name='سایز')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductsImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='images/products/', verbose_name='عکس')),
                ('isActive', models.BooleanField(verbose_name='فعال/غیر فعال')),
                ('isDelete', models.BooleanField(verbose_name='حذف شود/حذف نشود')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsModule.productsmodel', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'عکس محصول',
                'verbose_name_plural': 'عکس محصولات',
            },
        ),
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمل فرستنده')),
                ('name', models.CharField(max_length=100, verbose_name='نام فرستنده')),
                ('score', models.IntegerField(verbose_name='نمره فرستنده')),
                ('isActive', models.BooleanField(verbose_name='فعال/غیر فعال')),
                ('isDelete', models.BooleanField(verbose_name='حذف شود/حذف نشود')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productsModule.productsmodel', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
        migrations.CreateModel(
            name='StrengthsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150, verbose_name='متن')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsModule.commentsmodel', verbose_name='نظر')),
            ],
        ),
        migrations.CreateModel(
            name='WeakPointsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150, verbose_name='متن')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsModule.commentsmodel', verbose_name='نظر')),
            ],
        ),
    ]
