# Generated by Django 5.0.1 on 2024-03-24 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(verbose_name='عنوان در Url')),
                ('isActive', models.BooleanField(verbose_name='فعال/غیر فعال')),
                ('isDelete', models.BooleanField(verbose_name='حذف شود/حذف نشود')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='ColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(verbose_name='عنوان در Url')),
                ('isActive', models.BooleanField(verbose_name='فعال/غیر فعال')),
                ('isDelete', models.BooleanField(verbose_name='حذف شود/حذف نشود')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ ها',
            },
        ),
        migrations.CreateModel(
            name='SizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(verbose_name='عنوان در Url')),
                ('isActive', models.BooleanField(verbose_name='فعال/غیر فعال')),
                ('isDelete', models.BooleanField(verbose_name='حذف شود/حذف نشود')),
            ],
            options={
                'verbose_name': 'سایز',
                'verbose_name_plural': 'سایز ها',
            },
        ),
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('discount', models.IntegerField(null=True, verbose_name='درصد تخفیف')),
                ('count', models.IntegerField(verbose_name='تعداد در انبار')),
                ('slug', models.SlugField(verbose_name='عنوان در Url')),
                ('isActive', models.BooleanField(verbose_name='فعال/غیر فعال')),
                ('isDelete', models.BooleanField(verbose_name='حذف شود/حذف نشود')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsModule.categorymodel', verbose_name='دسته بندی')),
                ('color', models.ManyToManyField(to='productsModule.colormodel', verbose_name='رنگ ها')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsModule.sizemodel', verbose_name='سایز')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductsImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='images/products/', verbose_name='عکس')),
                ('isActive', models.BooleanField(verbose_name='فعال/غیر فعال')),
                ('isDelete', models.BooleanField(verbose_name='حذف شود/حذف نشود')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsModule.productsmodel', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'عکس محصول',
                'verbose_name_plural': 'عکس محصولات',
            },
        ),
    ]
