# Generated by Django 5.0.1 on 2024-03-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsModule', '0002_commentsmodel_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/category/', verbose_name='عکس'),
        ),
    ]
