# Generated by Django 5.0.1 on 2024-03-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsModule', '0002_categorymodel_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='عنوان در Url'),
        ),
        migrations.AlterField(
            model_name='colormodel',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='عنوان در Url'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='عنوان در Url'),
        ),
        migrations.AlterField(
            model_name='sizemodel',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='عنوان در Url'),
        ),
    ]
