# Generated by Django 5.0.1 on 2024-03-25 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsModule', '0003_alter_categorymodel_slug_alter_colormodel_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsmodel',
            name='description',
        ),
    ]
