# Generated by Django 5.0.1 on 2024-03-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsModule', '0004_remove_productsmodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsmodel',
            name='size',
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='size',
            field=models.ManyToManyField(to='productsModule.sizemodel', verbose_name='سایز'),
        ),
    ]
