# Generated by Django 5.0.1 on 2024-03-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsModule', '0004_alter_categorymodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weakpointscomment',
            name='comment',
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/category/', verbose_name='عکس'),
        ),
        migrations.DeleteModel(
            name='StrengthsComment',
        ),
        migrations.DeleteModel(
            name='WeakPointsComment',
        ),
    ]
