# Generated by Django 5.0.1 on 2024-04-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsModule', '0007_productsmodel_amazing_time_productsmodel_is_amazing'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='amazing_discount',
            field=models.IntegerField(default=0, verbose_name='درصد تخفیف شگفت انگیز'),
        ),
    ]
