# Generated by Django 5.0.1 on 2024-04-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSliderImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='images/home-page/sliders/', verbose_name='عکس')),
                ('isActive', models.BooleanField(verbose_name='فعال/غیر فعال')),
                ('isDelete', models.BooleanField(verbose_name='حذف شود/حذف نشود')),
            ],
            options={
                'verbose_name': 'عکس محصول',
                'verbose_name_plural': 'عکس محصولات',
            },
        ),
    ]
