# Generated by Django 5.0.1 on 2024-04-09 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeModule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagesliderimagemodel',
            options={'verbose_name': 'عکس اسلایدر', 'verbose_name_plural': 'عکس های اسلایدر'},
        ),
    ]
