# Generated by Django 5.0.1 on 2024-07-01 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartModule', '0001_initial'),
        ('productsModule', '0008_productsmodel_amazing_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartsitemsmodel',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productsModule.colormodel', verbose_name='رنگ انتخاب شده'),
        ),
        migrations.AddField(
            model_name='cartsitemsmodel',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productsModule.sizemodel', verbose_name='سایز انتخاب شده'),
        ),
    ]
