# Generated by Django 5.0.1 on 2024-07-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersPanelModule', '0002_alter_addressmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='حذف شده/نشده'),
        ),
    ]
