# Generated by Django 5.0.1 on 2024-03-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersModule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='emailActivateCode',
            field=models.CharField(max_length=6, verbose_name='کد فعالسازی'),
        ),
    ]
