# Generated by Django 5.0.1 on 2024-03-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersModule', '0002_alter_usersmodel_emailactivatecode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersmodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usersmodel',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='usersmodel',
            name='username',
        ),
        migrations.AddField(
            model_name='usersmodel',
            name='name',
            field=models.CharField(default=2, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
