# Generated by Django 5.0.1 on 2024-03-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersModule', '0004_alter_usersmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
