# Generated by Django 5.0.1 on 2024-03-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersModule', '0007_alter_usersmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='avatar',
            field=models.ImageField(null=True, upload_to='images/users_avatars/', verbose_name='عکس پروفایل'),
        ),
    ]
