# Generated by Django 5.0.1 on 2024-06-27 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsModule', '0008_productsmodel_amazing_discount'),
        ('usersModule', '0009_alter_usersmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='favorites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productsModule.productsmodel', verbose_name='محصولات مورد علاقه'),
        ),
    ]
