# Generated by Django 5.0.1 on 2024-06-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsModule', '0008_productsmodel_amazing_discount'),
        ('usersModule', '0010_usersmodel_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersmodel',
            name='favorites',
        ),
        migrations.AddField(
            model_name='usersmodel',
            name='favorites',
            field=models.ManyToManyField(to='productsModule.productsmodel', verbose_name='محصولات مورد علاقه'),
        ),
    ]
